# How to work with Python

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1HRZTjLezI_QNm8aFp6Wf5YzKmOg1fxXw?usp=sharing)

## What is Colab?

Colab, or "Colaboratory", allows you to write and execute Python in your browser, with 
- Zero configuration required
- Access to GPUs free of charge
- Easy sharing

Whether you're a **student**, a **data scientist** or an **AI researcher**, Colab can make your work easier.

## Getting started

The document you are reading is not a static web page, but an interactive environment called a **Colab notebook** that lets you write and execute code.

For example, here is a **code cell** with a short Python script that computes a value, stores it in a variable, and prints the result:

In [1]:
# run the code
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400

To execute the code in the above cell, select it with a click and then either press the play button to the left of the code, or use the keyboard shortcut "Command/Ctrl+Enter". To edit the code, just click the cell and start editing.

Variables that you define in one cell can later be used in other cells:

In [4]:
seconds_in_a_week = seconds_in_a_day
seconds_in_a_week

86400

**New cell**

You can add new cells by using the + CODE and + TEXT buttons that show when you hover between cells. These buttons are also in the toolbar above the notebook where they can be used to add a cell below the currently selected cell.

## Resources

Links work in Colab!
    
### Working woth notebooks in Colab


- [General information about Colaboratory](/notebooks/basic_features_overview.ipynb)
- [Markdown guide](/notebooks/markdown_guide.ipynb)
- [Importing libraries](/notebooks/snippets/importing_libraries.ipynb)
- [Saving notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/colab-github-demo.ipynb)

### Working with data

- [Downloading the data from Drive and Google Cloud Storage](/notebooks/io.ipynb)
- [Visualization of the data](/notebooks/charts.ipynb)



# Python

**Python** is a high-level, general-purpose programming language.

# Libraries

List of the most frequently used libraries:
 - <a href="http://numpy.org">Numpy</a>  is the short name for Numerical Python, which is a Python library predominantly used for technical and scientific computing. Its array-oriented computing capabilities make it an essential tool for fields such as linear algebra, statistical analysis, and machine learning.
 - <a href="http://numpy.org">SciPy</a> is a Python library used for scientific and technical computing. It is built on top of NumPy so it has additional functionalities for various scientific computing tasks. Optimization methods, integration, signal and image processing modules, statistics, linear algebra, splines, clustering and much more.
 -  <a href="http://pandas.pydata.org/">Pandas</a> is an open-source data manipulation library for Python. It is built on top of the NumPy library. It introduces two primary data structures Series and DataFrame. Series is a one-dimensional labelled data whereas DataFrame is a two-dimensional labelled data resuming a table.
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> is a machine-learning library that provides tools for data mining and analysis. It includes lots of machine learning algorithms for different tasks.
 - <a href="http://http://matplotlib.org/">matplotlib</a> is a data visualization library that allows developers to create static animated and interactive animations in Python. The graphs and plots it produces are extensively used for data visualization.

# Part 1 - Basics of Python

For applied purposes, it is important to master several aspects:

- Standart functions
- Variables
- Basics structures
- Functions
- Usage of libraries

## Standart functions

Functions - это маленькие программки, которые умеют выполнять какую-то операцию <br />
Functions can be <b>called</b>, после имени функции следуют круглые скобки, в которых указываются <b>аргументы</b> (над каким объектом будет выполнена операция) и <b>параметры </b> (с какими условиями)

### print()
Функция для вывода содержимого на экран. <br>
**Обязательно**: передать хотя бы какой-то объект, который нужно напечатать.

Ее полный синтаксис:

print(*objects, sep=' ', end='\n', file=sys.stdout, flush=False)¶
- objects: один или несколько объектов для вывода, перечисленные через запятую
- sep: разделитель между несколькими объектами; стандартно установлен пробел
- end: окончание строки; стандартно установлен перевод на новую строчку '\n'

In [6]:
print(5)

5


In [7]:
print(5, 6, 7, 8)

5 6 7 8


In [8]:
print(5, 6, 7, 8, sep='_')

5_6_7_8


In [9]:
print('October')

October


#### Задача 1

Выведите на экран фразу "Hello, world!"

In [10]:
# Напишите код и запустите


### Арифметические операции
- Сложение: +
- Вычитание: -
- Умножение: *
- Деление: /
- Возведение в степень: **
- Целочисленное деление: //
- Остаток от деления: %

In [11]:
print('Работаем с числами', 5, 'и', 2)
print(5 + 2)
print(5 - 2)
print(5*2)
print(5 / 2)
print( 5 // 2)
print('Результат остатка от деления:', 5 % 2)
print('Результат возведения в степени:', 5**2)

Работаем с числами 5 и 2
7
3
10
2.5
2
Результат остатка от деления: 1
Результат возведения в степени: 25


#### Задача 2

Представим, что у нас в активе $100, которые можно инвестировать с 10%-ным ежегодным доходом. <br>
Сколько денег мы заработаем через год? Выведите ответ на экран.

### Переменные и типы переменных

Результаты операций и манипуляций иногда нужно сохранять, поэтому мы определяем переменные - именованные объекты, которым присваиваем значения.

In [12]:
savings_2017 = 2000
savings_2016 = 1800
increase = ((2000 - 1800) / 1800)*100

In [13]:
# так можно подробно посмотреть информацию о функции
round?

In [14]:
#Вывести на печать % роста накоплений
print(round(increase), '%', sep='')

11%


Функция **type** позволяет определить, какого типа переменная нам дана или какого типа переменную мы записали.

In [15]:
print(type(savings_2017))
print(type(increase))

<class 'int'>
<class 'float'>


In [16]:
text = 'Monatery Savings in 2017'
print(type(text))

<class 'str'>


In [17]:
x = False
print(type(x))

<class 'bool'>


Если нужно поменять тип переменной, то полезны функции:

- int() - возвращает целочисленную переменную
- float() - возвращает нецелочисленную переменную
- bool() - возвращает булеву переменную
- str() - возвращает строковую переменную

In [18]:
print(savings_2017, type(savings_2017))
savings_2017_new = str(savings_2017)
print(savings_2017_new, type(savings_2017_new))
print('Savings ' +  'in 2017: ' + savings_2017_new)

2000 <class 'int'>
2000 <class 'str'>
Savings in 2017: 2000


In [19]:
print(int(savings_2017_new) - savings_2016)

200


#### Задача 4

Поправьте строчку кода так, чтобы она работала:

In [21]:
# print("I started with $" + savings_2016 + " and now have $" + savings_2017_new + ". Not good!")

### Листы

Четыре рассмотренных типа данных устроены так, что в одной переменной записано одно значение:
- int: целое число
- float: число с дробной частью
- str: текст
- bool: логическая переменная

Например, если мы хотим зафиксировать накопления членов семьи, мы можем создать ряд переменных и вписать туда информацию

In [22]:
savings1 = 500
savings2 = 1000
savings3 = 746
savings4 = 456

Но это не очень удобно, мы можем записать всю информацию в одной переменной:

In [23]:
savings_family = [500, 1000, 746, 2000]

Эта конструкция называется листом и является отдельным типом данных. К элементам листа можно обращаться по индексу:

In [24]:
print(savings_family[2])

746


In [25]:
print(savings_family[-1])

2000


А здесь - лист листов :)

In [26]:
savings_family = [['mom', 500], ['dad', 1000], ['brother', 746], ['me', 2000]]

In [27]:
s = 0
# Цикл, в котором суммируем все накопления
for member in savings_family:
    s = s + member[1]
print(s)

4246


In [28]:
print(savings_family)

[['mom', 500], ['dad', 1000], ['brother', 746], ['me', 2000]]


#### Задача 5

Создайте лист home, в котором записан название и метраж комнат в доме (kitchen - 10, bedroom - 12, bathroom - 5). Распечатайте лист.

Есть много методов (т.е. функций, которые присущи только листам) для работы с листами:

Методы
- list.append(x)	Добавляет элемент в конец списка
- list.extend(L)	Расширяет список list, добавляя в конец все элементы списка L
- list.insert(i, x)	Вставляет на i-ый элемент значение x
- list.remove(x)	Удаляет первый элемент в списке, имеющий значение x. ValueError, если такого элемента не существует
- list.pop([i])	Удаляет i-ый элемент и возвращает его. Если индекс не указан, удаляется последний элемент
- list.index(x, [start [, end]])	Возвращает положение первого элемента со значением x (при этом поиск ведется от start до end)
- list.count(x)	Возвращает количество элементов со значением x
- list.sort([key=функция])	Сортирует список на основе функции
- list.reverse()	Разворачивает список
- list.copy()	Поверхностная копия списка
- list.clear()	Очищает список

In [29]:
#удаляем запись про последнего члена семьи
savings_family.pop()
print(savings_family)

[['mom', 500], ['dad', 1000], ['brother', 746]]


In [30]:
#а теперь добавим
savings_family.append(['me', 2000])

In [31]:
#Создаём список из двух списков, в котором хранится информация о сбережениях дяди в 4000 и о сбережениях тети в 10000
savings_relatives = [['uncle', 4000], ['aunt', 10000]]

In [32]:
savings_family.extend(savings_relatives)
print(savings_family)

[['mom', 500], ['dad', 1000], ['brother', 746], ['me', 2000], ['uncle', 4000], ['aunt', 10000]]


#### Задача 6

Посчитайте сумму сбережений всей семьи

In [33]:
for member in savings_family:
    #ваш код здесь
    print(member)

['mom', 500]
['dad', 1000]
['brother', 746]
['me', 2000]
['uncle', 4000]
['aunt', 10000]


## Основные конструкции языка

### Логические выражения

По аналогии с арифметическими выражениями существуют логические выражения, которые могут быть истинными или ложными. Простое логическое выражение имеет вид <br />

<арифметическое выражение> <знак сравнения> <арифметическое выражение>. <br />

Например, если у нас есть переменные x и y с какими-то значениями, то логическое выражение <br /> x + y < 3y <br /> в качестве первого арифметического выражения имеет x + y, в качестве знака сравнения < (меньше), а второе арифметическое выражение в нём 3y.

<center>
    <table>
        <tr>
            <th>Логическое выражение </th>
            <th> Значение </th>
        </tr>
        <tr><td>&lt;</td><td> Меньше</td></tr>
        <tr><td>&gt;</td><td> Больше</td></tr>
        <tr><td>&lt;=</td><td> Меньше или равно</td></tr>
        <tr><td>&gt;=</td><td> Больше или равно</td></tr>
        <tr><td>==</td><td> Равно </td></tr>
        <tr><td>!=</td><td> Не равно</td></tr>
    </table>
</center>

In [34]:
x = 1 > 2
print(type(x))
print(x)
print(int(x))

<class 'bool'>
False
0


Чтобы записать сложное логическое выражение, часто бывает необходимо воспользоваться логическими связками "и", "или" и "не". В Питоне они обозначаются как and, or и not соответственно. Операции and и or являеются бинарными, т.е. должны быть записаны между операндами, например x < 3 or y > 2. Операция not - унарная и должна быть записана перед единственным своим операндом.

In [36]:
# Задайте 3 любых числа x, y, z:

# print(x == y)
# print(x > y and y < z)

#### Задача 7

Сравните, больше ли x 10. Результат распечатайте

In [37]:
x = 7


**Задача 8**

Сбережения мамы попадают в интервал с 300 до 500? Напишите логическое выражение, проверяющее это условие


In [38]:
savings_mom = 500



### Условный оператор

Наиболее частое применение логические выражения находят в условных операторах.

Синтаксис в питоне: <br />
**if** условие1:<br />
&emsp; команды<br />
**elif** условие2:<br />
&emsp; команды<br />
**elif** условие3:<br />
&emsp; команды<br />
**else**: <br />
&emsp; команды<br />

In [39]:
x = 5
y = 7
if x > y:
    print('X больше Y')
    print(x - y)
else:
    print(' ')
    print('Y не меньше, чем X')

 
Y не меньше, чем X


In [41]:
# x = int(input('Введите х '))
# y = int(input('Введите y '))
if x > y:
    print('X больше Y')
    print(x - y)
elif y > x:
    print('Y больше X')
    print(y - x)
else:
    print('X равно Y')

Y больше X
2


#### Задачи 9

1) Дана площадь кухни. Если она превышает 15 кв.м, то должна появиться строчка "Кухня большая!", в противном случае - "Кухня маленькая"

In [43]:
room = "kit"
area = 14.0

# if #ваш код здесь:
#     print()
# else:
#     print()

### Цикл while

Как только строчка кода выполнилась, она "забывается", т.е. чтобы повторить это действие, нужно явно прописать еще раз. Для многократного повторения одних и тех же действий используются циклические конструкции.

While переводится как "пока" и позволяет выполнять команды, до тех пор, пока условие верно. После окончания выполнения блока команд, относящихся к while, управление возвращается на строку с условием и, если оно выполнено, то выполнение блока команд повторяется, а если не выполнено, то продолжается выполнение команд, записанных после while.

Важно случайно не сделать бесконечный цикл!

**while** условие1:<br />
&emsp; команды<br />

Все команды пишутся с отступом.

In [44]:
temperature = 5
while temperature > 0:
    print('The weather is OK.')
    temperature = temperature - 1

The weather is OK.
The weather is OK.
The weather is OK.
The weather is OK.
The weather is OK.


#### Задача 10

По данному целому числу N распечатайте квадраты всех чисел, предшествующих N (включая N), в порядке убывания

**Образец**

Входные данные: <br />
3

Вывод программы: <br />
9<br />
4<br />
1<br />

In [45]:
N = 5
# Ваш код



### Цикл for

#### Функция range(n)
Создается объект класса range, внутри которого содержится арифметическая прогрессия в заданных диапазонах и с определенным шагом

Ее синтаксис:
- range(start, stop[, step])

In [46]:
print(range(5))
print(list(range(5)))
print(list(range(2, 7)))
print(list(range(2, 6, 2)))

range(0, 5)
[0, 1, 2, 3, 4]
[2, 3, 4, 5, 6]
[2, 4]


## Цикл for
Цикл for позволяет поочередно перебрать элементы из чего-нибудь итерируемого.

Ее синтаксис: <br />
**for** i **in** диапазон изменений i:<br />
&emsp; команды

Все команды пишутся с отступом

In [47]:
n = 5
for i in range(n + 1):
    print(i**2)

0
1
4
9
16
25


In [48]:
for color in ['red', 'green', 'yellow']:
    print(color, 'apple')

red apple
green apple
yellow apple


## Написание функций

Если какие-то операции надо повторять из раза в раз и нет готовых функций, то можно создать свою.

Синтаксис: <br />
**def** название функции(список аргументов):<br />
&emsp; команды<br />
&emsp; **return** результат выполнения функции<br />

Все команды пишутся с отступом.

Функция должна быть записана в любом месте до ее первого вызова.

In [50]:
def power(number, p):
    result = number**p
    return result

# number = int(input("Число "))
# p = int(input("Степень"))
# print(power(number, p))

#### Задача 11

Напишите функцию, которая по 2 сторонам прямоугольника возвращает его периметр.

In [52]:
# def rectangle(a, b):
    # Ваш код

a = 4
b = 10
# print(rectangle(a, b))

# Работа с NumPy

NumPy -- это модуль для python, который предоставляет общие математические и числовые операции в виде быстрых функций. Они обеспечивают функционал, который можно сравнить с функционалом MatLab. `NumPy` (Numeric Python) предоставляет базовые методы для манипуляции с большими массивами и матрицами. `SciPy` (Scientific Python) расширяет функционал numpy огромной коллекцией полезных алгоритмов, таких как минимизация, преобразование Фурье, регрессия, и другие прикладные математические техники.

Чтобы использовать (любую) библиотеку, нужно подгрузить ее в наш рабочий документ. <br>
Команда устроена так:


**import** название библиотеки


Для дальнейшего использования название библиотеки могут сократить, но тогда в загрузке указывают ее псевдоним


**import** название библиотеки **as** псевдоним

In [53]:
import numpy as np

Главной особенностью numpy является объект `array`. Массивы схожи со списками в python, исключая тот факт, что элементы массива должны иметь одинаковый тип данных, как `float` и `int`. С массивами можно проводить числовые операции с большим объемом информации в разы быстрее и, главное, намного эффективнее чем со списками.

Создание массива из списка:

In [54]:
a = np.array([1, 4, 5, 8], float)
print(type(a))

<class 'numpy.ndarray'>


Ко всем элементам можно получить доступ и манипулировать ими так же, как вы бы это делали с обычными списками:

In [55]:
# try to print element of array
print(a[0:2])

[1. 4.]


Массивы могут быть и многомерными. Вот пример двумерного массива (матрица):

In [56]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [57]:
print(a[:,1])

[2. 5.]


In [58]:
print('Размер массива:', a.shape)
print('Тип данных в массиве:', a.dtype)

Размер массива: (2, 3)
Тип данных в массиве: float64


Размер массива можно изменить при помощи методов `reshape`, `flatten`, `transpose`. С помощью `reshape` можно добавлять или удалять измерения в массиве, а также изменять количество элементов в каждом измерении.

In [59]:
a = np.array(range(10), float)
print('Старый размер:', a.shape)
a = a.reshape((5, 2))
print('Новый размер:', a.shape)

Старый размер: (10,)
Новый размер: (5, 2)


`transpose` - функция, позволяющяя менять порядок осей.

In [60]:
a = a.transpose()
print('Размер после transpose:', a.shape)

Размер после transpose: (2, 5)


In [61]:
# make array 3-dimentional with shape = (1, 2, 5)

# transpose it that it's shape = (2, 5, 1)


Функция `flatten` позволяет вытягивать массив, то есть из многомерного массива переконвертировать в одномерный.

In [62]:
a = a.flatten()
print('Размер вытянутого массива:', a.shape)

Размер вытянутого массива: (10,)


Арифметические операторы в массивах применяются поэлементно.

In [63]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print('b:', b)
print('a - b:', a - b)

b: [0 1 2 3]
a - b: [20 29 38 47]


In [64]:
print('b^5:', np.power(b, 3))

b^5: [ 0  1  8 27]


In [65]:
print('10 * sin(a):', 10 * np.sin(a))

10 * sin(a): [ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [66]:
print('Elements of a < 35:', a < 35)

Elements of a < 35: [ True  True False False]


Посмотрим на перемножение матриц:

In [68]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print('elementwise product:')
print(A * B)

print('matrix product')
print(A @ B)

print('another matrix product')
print(A.dot(B))

elementwise product:
[[2 0]
 [0 4]]
matrix product
[[5 4]
 [3 4]]
another matrix product
[[5 4]
 [3 4]]


В машинном обучении и науке о данных иногда вам придется работать со случайно сгенерированными данными. Различные методы `numpy` `random`
 существуют для генерации случайных целых чисел или массива `numpy` со случайными целыми числами.

Если мы инициализируем начальные условия с определенным начальным значением, то для этого начального значения всегда будут генерироваться одни и те же случайные числа. Это означает, что `numpy` `random` является детерминированным для данного начального значения.

In [69]:
np.random.seed(5)

Рассмотрим несколько функций для генерации случайных значений:

In [70]:
np.random.normal?

In [71]:
np.random.normal(loc = 1, scale = 1, size = 2)

array([1.44122749, 0.66912985])

In [72]:
# Generate 2-dimentional array from normal distribution


In [73]:
np.random.rand?

In [74]:
np.random.rand(2,2)

array([[0.20671916, 0.91861091],
       [0.48841119, 0.61174386]])

Больше информации об использовании `Numpy` можно найти в следующем [туториале](https://numpy.org/doc/stable/user/quickstart.html) .